### ISSUE TITLE
Minor: Firmware doesn't show point releases

### ISSUE THREAD

**Issue by akhepcat** [mrmp17/PLab-Vibration-Probe-FW#2]
the versions in the Release are sorted by point number  (.0.3, .0.4)   however the filenames  are all  .0.0

In addition, when copied to the device and rebooted, the 'info' command always returns .0.0

This makes it difficult to see what version the picoquake is actually running.

It's probably because the version is statically set in main.cpp

    main.cpp:static constexpr char FIRMWARE_VERSION[] =  "1.0.0";

and isn't being tied to the git tag, or to any other external incrementation.  

this carries over all existing tags (v1.0.3, v1.0.4, v1.1.1)

**Comment by nplan** [comment]
The github tag is the python package version. The latest firmware version is v1.0.0 and has been unchanged for the last couple of python package updates.
